### PR TITLE
Lazily load tables

### PR DESCRIPTION
**Pull request by SLieve**
@tuliren I think this should work for lazily loading tables.

### CODE REVIEW

**Comment by seancarr** [comment]
@SLieve, do you have an example of what type of error/exception this is solving for? That will help with the review.

**Comment by tuliren** [comment]
@SLieve I think you also need to make the static `TABLE` and `COLUMN` variables lazy-loading. Otherwise they will cause trouble during the db schema migration as well. This is also an opportunity to correct the naming convention (i.e., resolving the mistake I made that leads to compilation error in the generated code if the user has a column named `TBL`).

**Comment by tuliren** [comment]
Talked with @SLieve offline. The above statement is incorrect. `TABLE`s and `COLUMN`s won't affect production during the schema change.

**Comment by SLieve** [comment]
Upon further inspection of what Jack does when first loading tables, this PR won't solve what it was trying to solve.

**Pull request closed without merging**
