### PR TITLE
Release to Sonatype instead

### PR DESCRIPTION
**Pull request by joshk0**
following the method of LiveRamp/daemon_lib#26

### CODE REVIEW

**Comment by joshk0** [comment]
@tuliren meant to ask you if you knew anything about JACK build failure :)

**Comment by joshk0** [comment]
Here is the error.

```
[INFO] --- exec-maven-plugin:1.3.2:exec (generate-jack-test-sources) @ jack-test ---
/home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated
/home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:124:in `block (2 levels) in <class:Numeric>': stack level too deep (SystemStackError)
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	from /home/travis/build/LiveRamp/jack/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:131:in `block (2 levels) in <class:Numeric>'
	 ... 4980 levels...
	from ../jack-core/src/rb/jack.rb:40:in `block in run'
	from ../jack-core/src/rb/jack.rb:29:in `each'
	from ../jack-core/src/rb/jack.rb:29:in `run'
	from ../jack-core/src/rb/jack.rb:75:in `<main>'
```

**Comment by tuliren** [comment]
This is cause by ruby 2.4.x, which somehow led to this exception. I am debugging locally to see what is going on.

Meanwhile, given that all code has already been generated and java / ruby tests have passed before deployment, is it possible to skip code generation / unit tests in the deployment phrase?

**Comment by tuliren** [comment]
Here is the root cause:
https://stackoverflow.com/questions/41504106/ruby-2-4-and-rails-4-stack-level-too-deep-systemstackerror

**Comment by tuliren** [comment]
@joshk0, is there a way to enforce `deploy` to use ruby `2.3.0`? I am not able to figure out why it used ruby `2.4.1` to run `deploy`.

The alternative is to upgrade `activesupport` to `4.2.8`. However, this may not be a sustainable solution, as the ruby version may change again on travis ci's size, and then we will have to change the version of `activesupport` again.

**Comment by joshk0** [comment]
@tuliren Looks like the build passes now! Any other comments about releasing to sonatype (and eventually maven central?)

**Comment by tuliren** [comment]
Great! No other comments. :shipit:

**Pull request merged**
