### PR TITLE
Support where clauses for ids

### PR DESCRIPTION
**Pull request by michel-tricot**
Make it possible to do:
```
MyModel.query().whereId(myWhereClause).find()
```

Today it is only supported for non-id fields

### CODE REVIEW

**Comment by michel-tricot** [comment]
Code compiles, I still need to add some ```whereId``` tests. 

Unfortunately ```mvn test``` doesn't seem to work out of the box so I will have to play a little with my environment.

**Comment by michel-tricot** [comment]
A follow up task is to remove the hardcoded ```idIn``` and all the code associated with it.

**Comment by michel-tricot** [comment]
Should be all good

**Comment by bpodgursky** [comment]
@tuliren how does this look to you?  looks good to me.

**Comment by tuliren** [comment]
All looks good!

**Comment by michel-tricot** [comment]
@bpodgursky can you merge this PR?

**Pull request merged**
