### PR TITLE
update jdbc driver

### PR DESCRIPTION
**Pull request by dwarrier**
@rfaugeroux

---
This change is [Reviewable](https://reviewable.io/reviews/liveramp/jack/186)

### CODE REVIEW

**Comment by rfaugeroux** [comment]
@bpodgursky I think you had to change something to make this repository available, will it cause problems to have Jack depend on it?

**Comment by bpodgursky** [comment]
I added the mirror to http://redshift-maven-repository.s3-website-us-east-1.amazonaws.com/release in our public repo.  It will probably be confusing to anyone using this project who isn't using our public repo, but whatever.  Do you know how to force a rebuild to test?

**Comment by rfaugeroux** [comment]
Closing and opening the PR seems to do the trick

**Comment by rfaugeroux** [comment]
@dwarrier :shipit:

**Comment by sidoh** [comment]
https://travis-ci.org/LiveRamp/jack

there's a button to restart a build

**Comment by rfaugeroux** [comment]
I don't see it, maybe because we don't have the same permissions

**Comment by dwarrier** [comment]
Thanks guys! Appreciate the help.

**Comment by davinchia** [comment]
@dwarri is this still in-flight or can this be closed?

**Comment by dwarri** [comment]
@davinchia I can't even remember why we opened this now :/ feel free to close, thanks for checking.

**Comment by davinchia** [comment]
Closing!

**Pull request closed without merging**
